# Generated by Django 3.0.3 on 2020-03-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('From', models.CharField(max_length=120)),
                ('to', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('price_details', models.TextField(blank=True)),
                ('location', models.TextField()),
                ('day', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('star', models.PositiveIntegerField(default=0)),
                ('main_photo', models.ImageField(upload_to='static/images')),
                ('photo_1', models.ImageField(blank=True, upload_to='static/images')),
                ('photo_2', models.ImageField(blank=True, upload_to='static/images')),
                ('photo_3', models.ImageField(blank=True, upload_to='static/images')),
                ('photo_4', models.ImageField(blank=True, upload_to='static/images')),
                ('photo_5', models.ImageField(blank=True, upload_to='static/images')),
                ('photo_6', models.ImageField(blank=True, upload_to='static/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
