# Generated by Django 3.0.3 on 2020-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='package',
            name='From',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='package',
            name='day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='main_photo',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='to',
            field=models.CharField(max_length=120),
        ),
    ]
