# Generated by Django 3.0.3 on 2020-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200326_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
