# Generated by Django 3.0.3 on 2020-03-20 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_to', models.DateTimeField(auto_now_add=True)),
                ('updated_to', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_to', models.DateTimeField(auto_now_add=True)),
                ('updated_to', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('price_details', models.TextField(blank=True)),
                ('location_details', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=100)),
                ('member', models.PositiveIntegerField(default=0)),
                ('star', models.PositiveIntegerField(default=0)),
                ('best', models.BooleanField(default=False)),
                ('review_int', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_str', models.CharField(max_length=50)),
                ('main_photo', models.ImageField(upload_to='hotel/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='hotel/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='hotel/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='hotel/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='hotel/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='hotel/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='hotel/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.Location')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.Room_type')),
            ],
        ),
    ]
